Add missing import contextlib
```python-traceback
Traceback (most recent call last):
  File "/farm/venv/bin/plotman", line 33, in <module>
    sys.exit(load_entry_point('plotman', 'console_scripts', 'plotman')())
  File "/farm/plotman/src/plotman/plotman.py", line 125, in main
    interactive.run_interactive()
  File "/farm/plotman/src/plotman/interactive.py", line 328, in run_interactive
    curses.wrapper(curses_main)
  File "/home/altendky/.pyenv/versions/3.9.2/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/farm/plotman/src/plotman/interactive.py", line 167, in curses_main
    arch_jobs = archive.get_running_archive_jobs(dir_cfg['archive'])
  File "/farm/plotman/src/plotman/archive.py", line 76, in get_running_archive_jobs
    with contextlib.suppress(psutil.NoSuchProcess):
NameError: name 'contextlib' is not defined
```